### ISSUE TITLE
Does not launch on Mac OS Yosemite

### ISSUE THREAD

**Issue by collimarco** [sarahtattersall/PIPE#83]
Just downloaded PIPE-gui-5.0.0.jar, launched it... and nothing appears. After a few seconds I get an error message from the system that says to check the Console (the program to see logs on Mac) for errors.

**Comment by collimarco** [comment]
Here's the error I get launching it from command line:

```
$ java PIPE-gui-5.0.0.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: PIPE-gui-5/0/0/jar
Caused by: java.lang.ClassNotFoundException: PIPE-gui-5.0.0.jar
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

**Comment by sjdayday** [comment]
Hi Marco,

You can either just double-click on the jar in the Finder, or run it from
the command line as follows:

java -jar PIPE-gui-5.0.0.jar

regards,
Steve Doubleday

On Mon, Feb 23, 2015 at 4:44 AM, Marco Colli <notifications@github.com>
wrote:

> Here's the error I get launching it from command line:
>
> $ java PIPE-gui-5.0.0.jar
> Exception in thread "main" java.lang.NoClassDefFoundError: PIPE-gui-5/0/0/jar
> Caused by: java.lang.ClassNotFoundException: PIPE-gui-5.0.0.jar
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/83#issuecomment-75534989>.
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by sjdayday** [comment]
I should mention that if you double-click on the jar in Finder, depending on your security settings, you may get a message like this:  "PIPE-gui-5.0.0.jar can't be opened because it is from an unidentified developer."  (wording may differ; I'm still running Mavericks.)  

Go to System Preferences / Security & Privacy / General.   Under "Allow apps downloaded from", you will probably see a message like this:   "PIPE-gui-5.0.0.jar was blocked from opening because it is not from an identified developer"; click the "Open Anyway" button.   

If you don't see that message, then click the "Anywhere" radio button, and then open the jar, and then set "Allow apps downloaded from" back to its original setting.  After the jar has been opened once, I think it will open in the future without a prompt.   

regards,
Steve

**Comment by collimarco** [comment]
Thanks for the reply, but this doesn't solve the issue.

Here's what I get:

```
$ java -jar PIPE-gui-5.0.0.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: Pipe : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

The same problem probably occurs when I launch the app through the Finder, because, even if **permissions are correct**, I get the following alert:

```
Impossible to open the Java JAR file "PIPE-gui-5.0.0.jar "
Check the Console for possible error messages.
```

**Comment by collimarco** [comment]
```
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```

**Comment by sjdayday** [comment]
Hi Marco,

PIPE 5 requires java 1.7.  You'll need to upgrade your java version to run it.  

regards,
Steve

**Comment by sjdayday** [comment]
I've updated the release documentation to note the dependency on java 1.7:

https://github.com/sarahtattersall/PIPE/releases/tag/PIPE-5.0.0

**Comment by collimarco** [comment]
Ok, thanks!
