### ISSUE TITLE
Cannot load saved file.

### ISSUE THREAD

**Issue by layeredqueuing** [sarahtattersall/PIPE#96]
I created and saved a small net, then tried to reload it.  PIPE through an exception input processing.  

bash-3.2$ 
bash-3.2$ 2015-10-27 10:27:28.281 java[1067:59175] plugin com.google.GoogleDrive.FinderSyncAPIExtension invalidated
2015-10-27 10:27:28.281 java[1067:58860] plugin com.getdropbox.dropbox.garcon invalidated
Oct 27, 2015 10:27:28 AM com.sun.xml.internal.bind.v2.util.XmlFactory createParserFactory
SEVERE: null
org.xml.sax.SAXNotRecognizedException: http://javax.xml.XMLConstants/feature/secure-processing
	at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.setFeatures(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParserImpl(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.setFeature(Unknown Source)
	at com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:114)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:139)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
	at uk.ac.imperial.pipe.io.PetriNetIOImpl.read(PetriNetIOImpl.java:138)
	at uk.ac.imperial.pipe.models.manager.PetriNetManagerImpl.createFromFile(PetriNetManagerImpl.java:96)
	at pipe.controllers.application.PipeApplicationController.createNewTabFromFile(PipeApplicationController.java:168)
	at pipe.actions.gui.OpenAction.actionPerformed(OpenAction.java:51)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: org.xml.sax.SAXNotRecognizedException: http://javax.xml.XMLConstants/feature/secure-processing
	at com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:121)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:139)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
	at uk.ac.imperial.pipe.io.PetriNetIOImpl.read(PetriNetIOImpl.java:138)
	at uk.ac.imperial.pipe.models.manager.PetriNetManagerImpl.createFromFile(PetriNetManagerImpl.java:96)
	at pipe.controllers.application.PipeApplicationController.createNewTabFromFile(PipeApplicationController.java:168)
	at pipe.actions.gui.OpenAction.actionPerformed(OpenAction.java:51)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.xml.sax.SAXNotRecognizedException: http://javax.xml.XMLConstants/feature/secure-processing
	at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.setFeatures(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParserImpl(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.setFeature(Unknown Source)
	at com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:114)
	... 47 more

**Comment by sjdayday** [comment]
Would you include the file that you tried to load?  Thanks.  Steve

On Tue, Oct 27, 2015 at 7:32 AM, Layered Queueing Network Solvers <
notifications@github.com> wrote:

> I created and saved a small net, then tried to reload it. PIPE through an
> exception input processing.
>
> bash-3.2$
> bash-3.2$ 2015-10-27 10:27:28.281 java[1067:59175] plugin
> com.google.GoogleDrive.FinderSyncAPIExtension invalidated
> 2015-10-27 10:27:28.281 java[1067:58860] plugin
> com.getdropbox.dropbox.garcon invalidated
> Oct 27, 2015 10:27:28 AM com.sun.xml.internal.bind.v2.util.XmlFactory
> createParserFactory
> SEVERE: null
> org.xml.sax.SAXNotRecognizedException:
> http://javax.xml.XMLConstants/feature/secure-processing
> at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source)
> at org.apache.xerces.jaxp.SAXParserImpl.setFeatures(Unknown Source)
> at org.apache.xerces.jaxp.SAXParserImpl.(Unknown Source)
> at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParserImpl(Unknown
> Source)
> at org.apache.xerces.jaxp.SAXParserFactoryImpl.setFeature(Unknown Source)
> at
> com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:114)
> at
> com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:139)
> at
> javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
> at
> javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
> at uk.ac.imperial.pipe.io.PetriNetIOImpl.read(PetriNetIOImpl.java:138)
> at
> uk.ac.imperial.pipe.models.manager.PetriNetManagerImpl.createFromFile(PetriNetManagerImpl.java:96)
> at
> pipe.controllers.application.PipeApplicationController.createNewTabFromFile(PipeApplicationController.java:168)
> at pipe.actions.gui.OpenAction.actionPerformed(OpenAction.java:51)
> at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> at
> javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
> at
> javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
> at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
> at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
> at
> javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
> at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
> at java.awt.Component.processMouseEvent(Component.java:6525)
> at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
> at java.awt.Component.processEvent(Component.java:6290)
> at java.awt.Container.processEvent(Container.java:2234)
> at java.awt.Component.dispatchEventImpl(Component.java:4881)
> at java.awt.Container.dispatchEventImpl(Container.java:2292)
> at java.awt.Component.dispatchEvent(Component.java:4703)
> at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
> at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
> at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
> at java.awt.Container.dispatchEventImpl(Container.java:2278)
> at java.awt.Window.dispatchEventImpl(Window.java:2739)
> at java.awt.Component.dispatchEvent(Component.java:4703)
> at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
> at java.awt.EventQueue.access$400(EventQueue.java:97)
> at java.awt.EventQueue$3.run(EventQueue.java:697)
> at java.awt.EventQueue$3.run(EventQueue.java:691)
> at java.security.AccessController.doPrivileged(Native Method)
> at
> java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> at
> java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
> at java.awt.EventQueue$4.run(EventQueue.java:719)
> at java.awt.EventQueue$4.run(EventQueue.java:717)
> at java.security.AccessController.doPrivileged(Native Method)
> at
> java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
> at
> java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> at
> java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> at
> java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
>
> Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException:
> org.xml.sax.SAXNotRecognizedException:
> http://javax.xml.XMLConstants/feature/secure-processing
> at
> com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:121)
> at
> com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:139)
> at
> javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
> at
> javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
> at uk.ac.imperial.pipe.io.PetriNetIOImpl.read(PetriNetIOImpl.java:138)
> at
> uk.ac.imperial.pipe.models.manager.PetriNetManagerImpl.createFromFile(PetriNetManagerImpl.java:96)
> at
> pipe.controllers.application.PipeApplicationController.createNewTabFromFile(PipeApplicationController.java:168)
> at pipe.actions.gui.OpenAction.actionPerformed(OpenAction.java:51)
> at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> at
> javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
> at
> javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
> at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
> at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
> at
> javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
> at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
> at java.awt.Component.processMouseEvent(Component.java:6525)
> at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
> at java.awt.Component.processEvent(Component.java:6290)
> at java.awt.Container.processEvent(Container.java:2234)
> at java.awt.Component.dispatchEventImpl(Component.java:4881)
> at java.awt.Container.dispatchEventImpl(Container.java:2292)
> at java.awt.Component.dispatchEvent(Component.java:4703)
> at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
> at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
> at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
> at java.awt.Container.dispatchEventImpl(Container.java:2278)
> at java.awt.Window.dispatchEventImpl(Window.java:2739)
> at java.awt.Component.dispatchEvent(Component.java:4703)
> at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
> at java.awt.EventQueue.access$400(EventQueue.java:97)
> at java.awt.EventQueue$3.run(EventQueue.java:697)
> at java.awt.EventQueue$3.run(EventQueue.java:691)
> at java.security.AccessController.doPrivileged(Native Method)
> at
> java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> at
> java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
> at java.awt.EventQueue$4.run(EventQueue.java:719)
> at java.awt.EventQueue$4.run(EventQueue.java:717)
> at java.security.AccessController.doPrivileged(Native Method)
> at
> java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
> at
> java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> at
> java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> at
> java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Caused by: org.xml.sax.SAXNotRecognizedException:
> http://javax.xml.XMLConstants/feature/secure-processing
> at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source)
> at org.apache.xerces.jaxp.SAXParserImpl.setFeatures(Unknown Source)
> at org.apache.xerces.jaxp.SAXParserImpl.(Unknown Source)
> at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParserImpl(Unknown
> Source)
> at org.apache.xerces.jaxp.SAXParserFactoryImpl.setFeature(Unknown Source)
> at
> com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:114)
> ... 47 more
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/96>.
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by srottschaefer** [comment]
This looks very similar to the error I got, when I tried running PIPE with Java 8 (build with Java 7).
Are you by chance using Java 8 to run PIPE?

**Comment by layeredqueuing** [comment]
On 2015-10-28 4:15 AM, srottschaefer wrote:
>
> This looks very similar to the error I got, when I tried running PIPE 
> with Java 8 (build with Java 7).
> Are you by chance using Java 8 to run PIPE?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sarahtattersall/PIPE/issues/96#issuecomment-151759866>.
>
Yes.

bash-3.2$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

I guess that blows away the 'run anywhere' claim.
   ..greg

**Comment by sjdayday** [comment]
Nice catch.

Does the file open properly under Java 7?

Steve

On Wed, Oct 28, 2015 at 7:53 AM, Layered Queueing Network Solvers <
notifications@github.com> wrote:

> On 2015-10-28 4:15 AM, srottschaefer wrote:
> >
> > This looks very similar to the error I got, when I tried running PIPE
> > with Java 8 (build with Java 7).
> > Are you by chance using Java 8 to run PIPE?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/sarahtattersall/PIPE/issues/96#issuecomment-151759866>.
> >
> Yes.
>
> bash-3.2$ java -version
> java version "1.8.0_25"
> Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
> Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
>
> I guess that blows away the 'run anywhere' claim.
> ..greg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/issues/96#issuecomment-151871106>
> .
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by sjdayday** [comment]
Fixed in [PIPE 5.0.2 release](https://github.com/sarahtattersall/PIPE/releases/tag/PIPE-5.0.2), following  the [suggestion](https://github.com/sarahtattersall/PIPE/issues/105) from [dcduba](https://github.com/dcduba)  -- thanks!
